name: Scheduled NEURON CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # Run at 2am every day
    - cron:  '0 2 * * *'
  workflow_dispatch:
    inputs:
      azure_drop_url:
        description: 'Azure drop (artifacts) url'
      neuron_branch:
        description: 'NEURON branch to test'
        default: ''

defaults:
  run:
    shell: bash

jobs:
  run-reusable:
    name: Run build CI
    uses: ./.github/workflows/build-neuron-template.yml
    with:
      neuron_branch: ${{ github.event.inputs.neuron_branch }}
      azure_drop_url: ${{ github.event.inputs.azure_drop_url }}
